<?php

use App\Controllers\PublicController;
use App\Controllers\FarmerController;
use App\Controllers\AdminController;
use App\Controllers\Actions\ActionController;

return [
    // Public clean URLs
    ['GET', '/', [PublicController::class, 'home']],
    ['GET', '/home', [PublicController::class, 'home']],
    ['GET', '/login', [PublicController::class, 'login']],
    ['GET', '/register', [PublicController::class, 'register']],
    ['GET', '/logout', [ActionController::class, 'logout']],
    ['GET', '/products', [PublicController::class, 'products']],
    ['GET', '/product', [PublicController::class, 'product']],
    ['GET', '/markets', [PublicController::class, 'markets']],
    ['GET', '/farmers', [PublicController::class, 'farmers']],
    ['GET', '/cart', [PublicController::class, 'cart']],
    ['GET', '/checkout', [PublicController::class, 'checkout']],
    ['GET', '/orders', [PublicController::class, 'orders']],
    ['GET', '/order', [PublicController::class, 'order_view']],
    ['GET', '/favorites', [PublicController::class, 'favorites']],
    ['GET', '/profile', [PublicController::class, 'profile']],
    ['GET', '/notifications', [PublicController::class, 'notifications']],
    ['GET', '/assistant', [PublicController::class, 'assistant']],
    ['POST', '/assistant', [PublicController::class, 'assistant']],
    ['GET', '/dashboard', [PublicController::class, 'dashboard']],

    // Farmer clean URLs
    ['GET', '/farmer/home', [FarmerController::class, 'home']],
    ['GET', '/farmer/products', [FarmerController::class, 'products']],
    ['GET', '/farmer/product-form', [FarmerController::class, 'product_form']],
    ['GET', '/farmer/orders', [FarmerController::class, 'orders']],
    ['GET', '/farmer/profile', [FarmerController::class, 'profile']],
    ['GET', '/farmer/reviews', [FarmerController::class, 'reviews']],
    ['GET', '/farmer/sales', [FarmerController::class, 'sales']],
    ['GET', '/farmer/schedule', [FarmerController::class, 'schedule']],

    // Admin clean URLs
    ['GET', '/admin/home', [AdminController::class, 'home']],
    ['GET', '/admin/farmers', [AdminController::class, 'farmers']],
    ['GET', '/admin/customers', [AdminController::class, 'customers']],
    ['GET', '/admin/markets', [AdminController::class, 'markets']],
    ['GET', '/admin/categories', [AdminController::class, 'categories']],
    ['GET', '/admin/products', [AdminController::class, 'products']],
    ['GET', '/admin/reviews', [AdminController::class, 'reviews']],
    ['GET', '/admin/reports', [AdminController::class, 'reports']],
    ['GET', '/admin/notifications', [AdminController::class, 'notifications']],

    // POST action routes
    ['POST', '/actions/login.php', [ActionController::class, 'login']],
    ['POST', '/actions/register.php', [ActionController::class, 'register']],
    ['POST', '/actions/cart.php', [ActionController::class, 'cart']],
    ['POST', '/actions/checkout.php', [ActionController::class, 'checkout']],
    ['POST', '/actions/order.php', [ActionController::class, 'order']],
    ['POST', '/actions/favorite.php', [ActionController::class, 'favorite']],
    ['POST', '/actions/review.php', [ActionController::class, 'review']],
    ['POST', '/actions/profile.php', [ActionController::class, 'profile']],
    ['POST', '/actions/farmer_product.php', [ActionController::class, 'farmer_product']],
    ['POST', '/actions/farmer_order.php', [ActionController::class, 'farmer_order']],
    ['POST', '/actions/farmer_review.php', [ActionController::class, 'farmer_review']],
    ['POST', '/actions/farmer_profile.php', [ActionController::class, 'farmer_profile']],
    ['POST', '/actions/admin.php', [ActionController::class, 'admin']],
    // GET route needed for report downloads (download_report / download_saved_report),
    // which are read-only links, not form submissions.
    ['GET', '/actions/admin.php', [ActionController::class, 'admin']],

    // Legacy URLs remain supported so old bookmarks/forms do not break.
    ['GET', '/index.php', [PublicController::class, 'home']],
    ['GET', '/login.php', [PublicController::class, 'login']],
    ['GET', '/register.php', [PublicController::class, 'register']],
    ['GET', '/logout.php', [ActionController::class, 'logout']],
    ['GET', '/products.php', [PublicController::class, 'products']],
    ['GET', '/product.php', [PublicController::class, 'product']],
    ['GET', '/markets.php', [PublicController::class, 'markets']],
    ['GET', '/farmers.php', [PublicController::class, 'farmers']],
    ['GET', '/cart.php', [PublicController::class, 'cart']],
    ['GET', '/checkout.php', [PublicController::class, 'checkout']],
    ['GET', '/orders.php', [PublicController::class, 'orders']],
    ['GET', '/order_view.php', [PublicController::class, 'order_view']],
    ['GET', '/favorites.php', [PublicController::class, 'favorites']],
    ['GET', '/profile.php', [PublicController::class, 'profile']],
    ['GET', '/notifications.php', [PublicController::class, 'notifications']],
    ['GET', '/assistant.php', [PublicController::class, 'assistant']],
    ['GET', '/dashboard.php', [PublicController::class, 'dashboard']],
    ['GET', '/farmer/index.php', [FarmerController::class, 'home']],
    ['GET', '/farmer/products.php', [FarmerController::class, 'products']],
    ['GET', '/farmer/product_form.php', [FarmerController::class, 'product_form']],
    ['GET', '/farmer/orders.php', [FarmerController::class, 'orders']],
    ['GET', '/farmer/profile.php', [FarmerController::class, 'profile']],
    ['GET', '/farmer/reviews.php', [FarmerController::class, 'reviews']],
    ['GET', '/farmer/sales.php', [FarmerController::class, 'sales']],
    ['GET', '/farmer/schedule.php', [FarmerController::class, 'schedule']],
    ['GET', '/admin/index.php', [AdminController::class, 'home']],
    ['GET', '/admin/farmers.php', [AdminController::class, 'farmers']],
    ['GET', '/admin/customers.php', [AdminController::class, 'customers']],
    ['GET', '/admin/markets.php', [AdminController::class, 'markets']],
    ['GET', '/admin/categories.php', [AdminController::class, 'categories']],
    ['GET', '/admin/products.php', [AdminController::class, 'products']],
    ['GET', '/admin/reviews.php', [AdminController::class, 'reviews']],
    ['GET', '/admin/reports.php', [AdminController::class, 'reports']],
    ['GET', '/admin/notifications.php', [AdminController::class, 'notifications']],
];